# Generated by Django 5.0.2 on 2024-02-25 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_contact_contactabout_ourmission_ourstory_ourvision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OurStory_title', models.CharField(max_length=100)),
                ('OurStory_content', models.TextField()),
                ('OurMission_title', models.CharField(max_length=100)),
                ('OurMission_content', models.TextField()),
                ('OurVision_title', models.CharField(max_length=100)),
                ('OurVision_content', models.TextField()),
                ('TeamMember_name', models.CharField(max_length=100)),
                ('TeamMember_position', models.CharField(max_length=100)),
                ('ContactAbout_title', models.CharField(max_length=100)),
                ('ContactAbout_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactAbout',
        ),
        migrations.DeleteModel(
            name='OurMission',
        ),
        migrations.DeleteModel(
            name='OurStory',
        ),
        migrations.DeleteModel(
            name='OurVision',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category'),
        ),
    ]
