# Generated by Django 5.0.2 on 2024-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_about_delete_contactabout_delete_ourmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='ContactAbout_content',
            field=models.TextField(default=''),
        ),
    ]
